Seed set to 0
ERROR:TVLT:Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/mz/demo/MyNet/bert52'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent calls WITHOUT Sacred internals):
  File "./run.py", line 31, in main
    dm = MTDataModule(_config, dist=True)
  File "/home/mz/demo/MyNet/model/data/datamodules/multitask_datamodule.py", line 22, in __init__
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/home/mz/demo/MyNet/model/data/datamodules/multitask_datamodule.py", line 22, in <dictcomp>
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/home/mz/demo/MyNet/model/data/datamodules/mosei_datamodule.py", line 8, in __init__
    super().__init__(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/data/datamodules/datamodule_base.py", line 55, in __init__
    self.tokenizer = get_pretrained_tokenizer(tokenizer)
  File "/home/mz/demo/MyNet/model/data/datamodules/datamodule_base.py", line 25, in get_pretrained_tokenizer
    return BertTokenizer.from_pretrained(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2190, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/transformers/utils/hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/home/mz/demo/MyNet/bert52'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

Seed set to 0
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[rank: 1] Seed set to 0
[rank: 1] Seed set to 0
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA H100 PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Missing logger folder: /home/mz/demo/MyNet/tensorboardlog/cls_mosei_from__mae_vit_base_patch16_dec512d8b
Missing logger folder: /home/mz/demo/MyNet/tensorboardlog/cls_mosei_from__mae_vit_base_patch16_dec512d8b
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4]

  | Name                  | Type        | Params
------------------------------------------------------
0 | transformer           | TVLT        | 111 M 
1 | msaf                  | MSAFLSTMNet | 345 M 
2 | train_mosei_accuracy2 | Accuracy    | 0     
3 | train_mosei_f1score   | F1Score     | 0     
4 | train_mosei_loss      | Scalar      | 0     
5 | val_mosei_accuracy2   | Accuracy    | 0     
6 | val_mosei_f1score     | F1Score     | 0     
7 | val_mosei_loss        | Scalar      | 0     
------------------------------------------------------
457 M     Trainable params
0         Non-trainable params
457 M     Total params
1,830.099 Total estimated model params size (MB)

Dataset Statistics:
Total samples: 16327
Positive samples: 11588, Negative samples: 4739
Pos/Neg ratio: 2.45
Sample weights - Positive: 0.70, Negative: 1.72
Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Dataset Statistics:
Total samples: 16327
Positive samples: 11588, Negative samples: 4739
Pos/Neg ratio: 2.45
Sample weights - Positive: 0.70, Negative: 1.72
Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]ERROR:TVLT:Failed after 0:00:16!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/mz/demo/MyNet/run.py", line 106, in main
    trainer.fit(model, datamodule=dm)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1034, in _run_stage
    self._run_sanity_check()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1063, in _run_sanity_check
    val_loop.run()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 402, in validation_step
    return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 628, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1636, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1454, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 621, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 289, in validation_step
    output = self(batch)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 255, in forward
    ret.update(objectives.compute_mosei(self, batch))
  File "/home/mz/demo/MyNet/model/TVLTmodules/objectives.py", line 464, in compute_mosei
    mosei_score = pl_module.infer(batch, mask_text=False, mask_visual=False)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 205, in infer
    hidden_size = self.msaf(av, batch[txtkey][0],batch['attention_mask'][0])
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/NHFNet/networks/msaf_mosei.py", line 213, in forward
    l_av = self.cross_transformer(audio_visual_feature, result1, result1)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/fusion_module.py", line 245, in forward
    gate = torch.sigmoid(self.fusion_layer(all_states))
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MultiModalFusionEncoder' object has no attribute 'fusion_layer'

ERROR:TVLT:Failed after 0:00:32!
Traceback (most recent calls WITHOUT Sacred internals):
  File "./run.py", line 106, in main
    trainer.fit(model, datamodule=dm)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1034, in _run_stage
    self._run_sanity_check()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1063, in _run_sanity_check
    val_loop.run()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 402, in validation_step
    return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 628, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1636, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1454, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 621, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 289, in validation_step
    output = self(batch)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 255, in forward
    ret.update(objectives.compute_mosei(self, batch))
  File "/home/mz/demo/MyNet/model/TVLTmodules/objectives.py", line 464, in compute_mosei
    mosei_score = pl_module.infer(batch, mask_text=False, mask_visual=False)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 205, in infer
    hidden_size = self.msaf(av, batch[txtkey][0],batch['attention_mask'][0])
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/NHFNet/networks/msaf_mosei.py", line 213, in forward
    l_av = self.cross_transformer(audio_visual_feature, result1, result1)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/fusion_module.py", line 245, in forward
    gate = torch.sigmoid(self.fusion_layer(all_states))
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MultiModalFusionEncoder' object has no attribute 'fusion_layer'

                                                                   [rank0]:[W126 11:46:57.645723422 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Seed set to 0
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[rank: 1] Seed set to 0
[rank: 1] Seed set to 0
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA H100 PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4]

  | Name                  | Type        | Params
------------------------------------------------------
0 | transformer           | TVLT        | 111 M 
1 | msaf                  | MSAFLSTMNet | 345 M 
2 | train_mosei_accuracy2 | Accuracy    | 0     
3 | train_mosei_f1score   | F1Score     | 0     
4 | train_mosei_loss      | Scalar      | 0     
5 | val_mosei_accuracy2   | Accuracy    | 0     
6 | val_mosei_f1score     | F1Score     | 0     
7 | val_mosei_loss        | Scalar      | 0     
------------------------------------------------------
457 M     Trainable params
0         Non-trainable params
457 M     Total params
1,830.099 Total estimated model params size (MB)

Dataset Statistics:
Total samples: 16327
Positive samples: 11588, Negative samples: 4739
Pos/Neg ratio: 2.45
Sample weights - Positive: 0.70, Negative: 1.72
Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Dataset Statistics:
Total samples: 16327
Positive samples: 11588, Negative samples: 4739
Pos/Neg ratio: 2.45
Sample weights - Positive: 0.70, Negative: 1.72
Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]ERROR:TVLT:Failed after 0:00:16!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/mz/demo/MyNet/run.py", line 106, in main
    trainer.fit(model, datamodule=dm)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1034, in _run_stage
    self._run_sanity_check()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1063, in _run_sanity_check
    val_loop.run()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 402, in validation_step
    return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 628, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1636, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1454, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 621, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 289, in validation_step
    output = self(batch)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 255, in forward
    ret.update(objectives.compute_mosei(self, batch))
  File "/home/mz/demo/MyNet/model/TVLTmodules/objectives.py", line 464, in compute_mosei
    mosei_score = pl_module.infer(batch, mask_text=False, mask_visual=False)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 205, in infer
    hidden_size = self.msaf(av, batch[txtkey][0],batch['attention_mask'][0])
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/NHFNet/networks/msaf_mosei.py", line 213, in forward
    l_av = self.cross_transformer(audio_visual_feature, result1, result1)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/fusion_module.py", line 245, in forward
    gate = torch.sigmoid(self.fusion_layer(all_states))
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MultiModalFusionEncoder' object has no attribute 'fusion_layer'

ERROR:TVLT:Failed after 0:00:32!
Traceback (most recent calls WITHOUT Sacred internals):
  File "./run.py", line 106, in main
    trainer.fit(model, datamodule=dm)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1034, in _run_stage
    self._run_sanity_check()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1063, in _run_sanity_check
    val_loop.run()
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 402, in validation_step
    return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 628, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1636, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1454, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 621, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 289, in validation_step
    output = self(batch)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 255, in forward
    ret.update(objectives.compute_mosei(self, batch))
  File "/home/mz/demo/MyNet/model/TVLTmodules/objectives.py", line 464, in compute_mosei
    mosei_score = pl_module.infer(batch, mask_text=False, mask_visual=False)
  File "/home/mz/demo/MyNet/model/TVLTmodules/model_module.py", line 205, in infer
    hidden_size = self.msaf(av, batch[txtkey][0],batch['attention_mask'][0])
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/NHFNet/networks/msaf_mosei.py", line 213, in forward
    l_av = self.cross_transformer(audio_visual_feature, result1, result1)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mz/demo/MyNet/model/TVLTmodules/fusion_module.py", line 245, in forward
    gate = torch.sigmoid(self.fusion_layer(all_states))
  File "/home/mz/anaconda3/envs/new_NFH/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MultiModalFusionEncoder' object has no attribute 'fusion_layer'

                                                                   [rank0]:[W126 11:54:12.781971833 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
